export enum AccordionConstants {
  SPRING = 'spring',
  QUARKUS = 'quarkus',
  ANGULAR = 'angular',
  JAVA = 'java',
  HIBERNATE = 'hibernate',
  MYSQL = 'mysql',
  ORACLE = 'oracle',
  POSTGRESQL = 'postgresql',
  WEBDEVELOPER = 'web developer',
  HTML = 'html',
  CSS = 'css',
  JAVASCRIPT = 'javascript',
  FRONTEND = 'frontend',
  NETWORKING = 'networking',
  KALI = 'kali',
  CEH = 'ceh',
  COLLEGE = 'college',
}
